language: php

matrix:
    include:
        - php: 7.1
          env: DEPENDENCIES='dev' lint=1
        - php: 7.1
          env: DEPENDENCIES='low'
        - php: 7.2
          env: DEPENDENCIES='dev' lint=1
        - php: 7.2
          env: DEPENDENCIES='low'
        - php: 7.3
          env: DEPENDENCIES='dev' lint=1
        - php: 7.3
          env: DEPENDENCIES='low'
    fast_finish: true

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - phpenv config-rm xdebug.ini || echo "xdebug not available"
    - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - if [[ $lint = 1 ]]; then wget https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v2.6.0/php-cs-fixer.phar; fi
    - if [[ $lint = 1 ]]; then composer global require --dev 'phpstan/phpstan:^0.8'; fi
    - export PATH="$PATH:$HOME/.composer/vendor/bin"

install:
    - if [ "$DEPENDENCIES" == "dev" ]; then composer config minimum-stability dev; fi;
    - if [ "$DEPENDENCIES" != "low" ]; then composer update --prefer-dist --no-progress --no-suggest --ansi; fi;
    - if [ "$DEPENDENCIES" == "low" ]; then composer update --prefer-dist --no-progress --no-suggest --ansi --prefer-lowest; fi;

script:
    - export SYMFONY_PHPUNIT_VERSION=7.5.6
    - export SYMFONY_PHPUNIT_REMOVE="symfony/yaml"
    - export SYMFONY_DEPRECATIONS_HELPER=strict
    - vendor/bin/simple-phpunit --verbose
    - if [[ $lint = 1 ]]; then php php-cs-fixer.phar fix --dry-run --diff --no-ansi; fi
    #- if [[ $lint = 1 ]]; then phpstan analyse -c phpstan.neon -l5 --ansi src tests; fi # temporarily disabled
