language: php

matrix:
    include:
        - php: 5.6
        - php: 7.0
          env: DEPENDENCIES='dev'
        - php: 7.1
          env: DEPENDENCIES='low'
    fast_finish: true

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - phpenv config-rm xdebug.ini || echo "xdebug not available"

install:
    - if [ "$DEPENDENCIES" == "dev" ]; then composer config minimum-stability dev; fi;
    - if [ "$DEPENDENCIES" != "low" ]; then composer update --prefer-dist --no-progress --no-suggest --ansi; fi;
    - if [ "$DEPENDENCIES" == "low" ]; then composer update --prefer-dist --no-progress --no-suggest --ansi --prefer-lowest; fi;

script:
    - export SYMFONY_PHPUNIT_VERSION=5.7.1
    - export SYMFONY_PHPUNIT_REMOVE="symfony/yaml"
    - export SYMFONY_DEPRECATIONS_HELPER=strict
    - vendor/bin/simple-phpunit --verbose
